### get photo metadata
GET http://localhost:3000/api/filters/metadata/1684360621425 HTTP/1.1

### edit photo
### options:
### - rotate - {"deg":90}
### - resize - {"width":150,"height":97}
### - reformat - {}
### - crop - { "width": 200, "height": 200, "left": 20, "top": 20 }
### - grayscale - {}
### - flip - {}
### - flop - {}
### - negate - {}
### - tint - {"r":255,"g":0,"b":0}
PATCH http://localhost:3000/api/filters HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCR1dGNaZmNBdVlSRWM1dDlGMm8wdEouT2p6U3N3alNCaDRON3VBQm05WHhXRmFEYmZzS3lGbSIsImlhdCI6MTY4NTkwMDk0OSwiZXhwIjoxNjg1OTAxNTQ5fQ.8SX8w5EDp_N5R2jkpCN4LbSFANU1vnPF9d2PHdG8Gx0
Content-Type: application/json

{
    "id":1685979812924,
    "filter":"tint",
    "options":{"r":255,"g":0,"b":0}
}

### get photo
GET http://localhost:3000/api/getfile/1685885562013
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCQxYVBoakVtaERoM2Fmd3prN1Yya0lPU1U5LmJITXZYeHBjdVBsaG12QVB0VVoyelpZUE0yNiIsImlhdCI6MTY4NTg3MDM1MywiZXhwIjoxNjg1ODcwOTUzfQ.MoHXTd0O2MepLUF1aTRDLibKauC3UlzxmjsCccZrxF0
### get filtered photo
GET http://localhost:3000/api/getfile/1685198174083/tint

