### get photo metadata
GET http://localhost:3000/api/filters/metadata/1684360621425 HTTP/1.1

### edit photo
### options:
### - rotate - {"deg":90}
### - resize - {"width":150,"height":97}
### - reformat - {}
### - crop - { "width": 200, "height": 200, "left": 20, "top": 20 }
### - grayscale - {}
### - flip - {}
### - flop - {}
### - negate - {}
### - tint - {"r":255,"g":0,"b":0}
PATCH http://localhost:3000/api/filters HTTP/1.1
Content-Type: application/json

{
    "id":1685198174083,
    "filter":"tint",
    "options":{"r":255,"g":0,"b":0}
}

### get photo
GET http://localhost:3000/api/getfile/1685197685595

### get filtered photo
GET http://localhost:3000/api/getfile/1685198174083/tint

