POST http://localhost:3000/api/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.jpg"
Content-Type: image/jpeg

< ./input.jpg

------FormBoundary1234
Content-Disposition: form-data; name="album"
Content-Type: text/plain

album
------FormBoundary1234

#####

GET http://localhost:3000/api/photos HTTP/1.1

####
GET http://localhost:3000/api/photos/1681720626953 HTTP/1.1

###
PATCH http://localhost:3000/api/photos HTTP/1.1
Content-Type: application/json

{
    "id":1681720643823,
    "change":"zmiana 2"
}

####
DELETE http://localhost:3000/api/photos/1681720626953 HTTP/1.1  

### 
GET http://localhost:3000/api/photos/album@ca.som HTTP/1.1




