###
GET http://localhost:3000/api/profile HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im5hbWVAZW1haWwucGwiLCJwYXNzd29yZCI6IiQyYSQxMCRRdWsvV2EwdllJOU5uQlk2aTN1aDhPam9RelBuMXVNWjZQYXJzNVpSc2lYNU1FVER4SVBjcSIsImlhdCI6MTY4NTM0Nzg2NSwiZXhwIjoxNjg1MzQ4NDY1fQ.1Czf9q5VY2n4baCnmWoSgKyhwNjC8XOZXQqHMxyeiWc
###
PATCH http://localhost:3000/api/profile HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJwYXNzd29yZCI6IiQyYSQxMCRnZVVSM2VlMzlXQnY0cElsM2UxVEwuQlF6eS9uS09jWVoyNDZBcUhGR0JXMWZLRFZadTlFQyIsImlhdCI6MTY4NTk5OTQ4MSwiZXhwIjoxNjg2MDAwMDgxfQ.wdCVvqiWVXP6u7O_r9PdhWuhLYfLO8gsuY6VOqMtYyU
Content-Type: "application/json"


{
    "name":"dominik",
    "email":"a@a.com"
    
}
